services:
  nutritrack-backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/api-app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nutritrack  
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgAdmin:/var/lib/pgadmin
      - ./pgAdmin:/var/lib/pgadmin/storage

volumes:
  db:
  pgAdmin: