services:
  nutritrack-backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/api-app
      
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nutritack
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgAdmin:/var/lib/pgadmin
      - ./pgAdmin:/var/lib/pgadmin/storage

volumes:
  db:
  pgAdmin:
